name: Reusable testing workflow

on:
  workflow_call:
    inputs:
      base_ref:
        required: true
        type: string
      folder:
        required: true
        type: string
      head_ref:
        required: false
        type: string
      include:
        required: true
        type: string
      repository:
        required: true
        type: string

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        folder: ${{ fromJSON(inputs.folder) }}
        os: [ubuntu-latest, windows-latest]
        release: [R2023b]
        include: ${{ fromJSON(inputs.include) }}
        exclude:
          - os: ubuntu-latest
            folder: Mooring
    name: "${{ matrix.folder }} - ${{ matrix.os }} - ${{ matrix.release }}"
    timeout-minutes: 45
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: true
          ref: ${{ inputs.head_ref }}
          repository: ${{ inputs.repository }}
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Check out WEC-Sim
        uses: actions/checkout@v4
        with:
          repository: WEC-Sim/WEC-Sim
          ref: ${{ inputs.base_ref }}
          path: './WEC-Sim'
      - name: Check out MoorDyn
        if: matrix.folder == 'Mooring'
        uses: actions/checkout@v4
        with:
          repository: WEC-Sim/MoorDyn
          fetch-depth: 2  # Fetch the last 2 commits
          path: './MoorDyn'
      - name: Fetch second-to-last commit
        run: |
          cd MoorDyn

          # Check the number of commits
          COMMIT_COUNT=$(git rev-list --count HEAD)

          if [ "$COMMIT_COUNT" -lt 2 ]; then
            echo "Not enough commits to checkout the second-to-last commit."
            exit 1
          fi
          
          # Get the second-to-last commit hash
          SECOND_TO_LAST_COMMIT=$(git rev-parse HEAD~1)

          # Output the commit hash
          echo "Second-to-last commit: $SECOND_TO_LAST_COMMIT"

          # Optionally, you can check out the second-to-last commit
          git checkout $SECOND_TO_LAST_COMMIT
        shell: bash  # Specify that this step should run in Bash
      - name: Copy MoorDyn Files
        if: matrix.folder == 'Mooring'
        run: |
            cp * ../WEC-Sim/source/functions/moorDyn
            ls ../WEC-Sim/source/functions/moorDyn
        shell: bash
        working-directory: './MoorDyn'
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: ${{ matrix.products }}
          release: ${{ matrix.release }}
      - name: Start display server (Desalination on Linux)
        if: matrix.folder == 'Desalination' && matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
      - name: Install WEC-Sim, run tests and generate artifacts
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath(genpath('WEC-Sim/source'));
            results = wecSimAppTest("${{ matrix.folder }}"),
            assertSuccess(results);
