name: Test WEC-Sim dev branch
on:
  workflow_dispatch: {}
  repository_dispatch:
    types:
      - wecsim-dev
concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  main:
    uses: ./.github/workflows/all-tests-reusable.yml
    with:
      client_payload: ${{ toJSON(github.event.client_payload) }}
